providers:
  NistAPI: false
  PacketStormSecurityAPI: true
  OpenCVEAPI: true
  ExploitDBAPI: true
  GitHubAdvisoryAPI: true
  VulnersAPI: false
  CISAKEVAPI: true

enrichment:
  sources:
    vulners: true
    github: true
    cisa_kev: true