providers:
  NistAPI: false
  NistCachedAPI: true
  PacketStormSecurityAPI: true
  OpenCVEAPI: true
  ExploitDBAPI: true
  GitHubAdvisoryAPI: true
  VulnersAPI: false
  CISAKEVAPI: true
  RAPID7: true

enrichment:
  sources:
    vulners: true
    github: false
    github_cached: true
    cisa_kev: true
    github_poc: false
    github_poc_cached: true
    nist_cached: true